### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by nickmcintyre** [JithinKS97/dynamic-learning-app#4]
@JithinKS97 I just got the app running on my machine and am interested in contributing to the project. Would you consider adopting a standard [open source license](https://choosealicense.com/)?

**Comment by JithinKS97** [comment]
This project was started as a part of Google Summer Of Code. So it has open source license. Very glad that you are interested in contributing. Do you have in your mind any specific feature that you wish to implement/improve?

**Comment by nickmcintyre** [comment]
The source code is definitely available, but it'd be helpful to include a license that covers contributions and usage. For example, p5.js uses the [LGPL](https://github.com/processing/p5.js/blob/master/license.txt) and ml5.js uses the [MIT License](https://github.com/ml5js/ml5-library/blob/development/LICENSE).

As for features, I have a few ideas and will open new issues over the coming days.

**Comment by JithinKS97** [comment]
I decided to include the project under LGPL licensing.
MIT was ruled out because we don't anybody  to completely copy our works and commercialise it.
GPL was ruled out because if any private parties find any part of the work that we did to be useful for them, they may be allowed to use it.
