### ISSUE TITLE
Lesson descriptions

### ISSUE THREAD

**Issue by nickmcintyre** [JithinKS97/dynamic-learning-app#5]
It would be helpful to include a few additional fields to summarize and organize lessons. I think teachers would have an easier time adopting lessons if they had a clear picture of where each fits in their existing curriculum. We could start with the following:

- Subject
- Topic
- Learning Objective(s)
- In-class Activities
- References/Resources
- Assessments
- Standards

**Comment by Anu-Asok** [comment]
Hi @nickmcintyre! I'm also working with @JithinKS97. I think this is a good idea and would benefit teachers. We are thinking of integrating a text editor into the Lessonplan creator where the teachers can use it to add necessary details into it.
Check out [https://www.slatejs.org/#/rich-text](SlateJS) 
This is the tool that we think of using. What's your opinion?

**Comment by nickmcintyre** [comment]
Slate looks really promising as an upgrade for the existing text area in the creator and generally across the app. My thinking here is more along the lines of tags and similar metadata.

**Comment by JithinKS97** [comment]
I think we can include an option in Lessonplan creator that allows the teacher to add these additional details if needed. May be by opening a model box and collecting these detail?

**Comment by nickmcintyre** [comment]
That sounds great @JithinKS97.

**Comment by jashi202jg** [comment]
Hi @nickmcintyre! I'm also interested in contributing to this project and appreciate your ideas. But, I was wondering what do you mean by Assessments and Standards in this context?

**Comment by nickmcintyre** [comment]
Hey @jashi202jg! Glad to see you're interested in jumping on board.

My experience is limited to public high school in Texas. We submit lesson plans for review weekly and are required to include all of the fields listed.

As a rule of thumb, learning activities (interacting with a simulation) should be tied to an assessment of learning. That may be a quick written reflection, a multiple choice question, a discussion, or an open-ended problem. You could think of them as a sort of unit test–did the student pick up what we put down? It might be helpful to suggest assessments that teachers can adapt.

In terms of standards, I must align my lessons to the [TEKS](https://en.wikipedia.org/wiki/Texas_Essential_Knowledge_and_Skills) and many teachers work within similar standards (e.g., [Common Core](http://www.corestandards.org/)). It might be helpful to list applicable standards to encourage adoption.

**Comment by JithinKS97** [comment]
@nickmcintyre, a pull request from @jashi202jg was merged to solve this issue.... Please take a look

**Comment by JithinKS97** [comment]
Solved with #12

**Comment by JithinKS97** [comment]
Solved with PR #12
