### ISSUE TITLE
Lessonplan drawing

### ISSUE THREAD

**Issue by nickmcintyre** [JithinKS97/dynamic-learning-app#8]
The Lessonplan creator might benefit from a few additional drawing capabilities. Primitives like line segments, rectangles, and ellipses would probably cover most use cases. Color fill, borders, rotation, and copy/paste would round out a minimal feature set.

It'd be neat to implement this with p5.js.

**Comment by JithinKS97** [comment]
Anybody taking up this issue, be sure to checkout 
http://fabricjs.com/demos/

**Comment by JithinKS97** [comment]
I'm thinking of taking up this issue.

For implementing this, we need to migrate to fabric.js (http://fabricjs.com/fabric-intro-part-1) from drawingboard.js (https://github.com/Leimi/drawingboard.js#drawingboardjs)

Since drawingboard.js makes use of string to store the drawings and fabric.js makes use of objects to store the same, we might loss all the drawings in the existing lessonplans.

**Comment by nickmcintyre** [comment]
Awesome @JithinKS97! Just updated my fork and started playing with the canvas–it really is smooth.

I noticed that drawings are scaled to fit in the left half of the canvas, presumably to leave room for embedding simulations. If so, it may be more intuitive to label and/or color code distinct regions of the drawing board to avoid distortions.

**Comment by JithinKS97** [comment]
Does the scaling occur after you draw it onto the canvas? This is not intended and might be a bug.  Let me look into it.

**Comment by nickmcintyre** [comment]
Yep. I observe the behavior using Firefox, Chrome, and Safari on macOS.

**Comment by JithinKS97** [comment]
Solved the issue 82da47d0bbcdf805cabc9acc4ac8a95d73fb8146

**Comment by nickmcintyre** [comment]
Looks good!

**Comment by JithinKS97** [comment]
I've added rectangle drawing tool, similarly other shapes can be easily added.

**Comment by nickmcintyre** [comment]
Just tinkered with the new shapes–they work really well!

**Comment by JithinKS97** [comment]
Implemented all the features that @nickmcintyre has asked

1) line segment
2) rectangle
3) ellipse
4) fill - (Change fill by selecting an object and selecting a color from the palette)
5) border
6) Rotation
7) Copy and paste (Select object and press Ctrl + C, Ctrl + V to paste)

**Comment by JithinKS97** [comment]
Closing the issue

**Comment by JithinKS97** [comment]
@all-contributors please add @JithinKS97 for infrastructure, tests and code
